package app;

public enum Genre {
    HORROR, ROMANCE, THRILLER, FANTASY,
    ACTION, BIOGRAPHY, ADVENTURE, ANTHOLOGY,
    CHILDREN, DRAMA, FAIRYTALE, COOKBOOKS,
    HISTORICAL_FICTION, POETRY, SATIRE, SCIENCE_FICTION,
    SUSPENSE, WESTERN, DYSTOPIAN, LITERARY,
    MYSTERY, PARANORMAL, GRAPHIC_NOVEL, HISTORY, HUMOR,
    RELIGION, TECHNOLOGY, POLITICS, TRAVEL
}

