@startuml
'https://plantuml.com/class-diagram

set separator ::
abstract class dogs::Dog {
    ~ name: String
    ---
    + setName(name: String): void
    + getName(): String
    {abstract} + bark(): void
}

class dogs::WatchDog {
    - taxId: String
    ---
    + bark(): void
}

Dog <|-- WatchDog

class App {
    - dog: Dog
    - wd: WatchDog
}

App -> Dog
App -> WatchDog
@enduml