@startuml
'https://plantuml.com/class-diagram

set separator ::
abstract class domain::Animal {
    - id: long
    ---
    + Animal(id: long)
    + getId(): long
    ---
    + {abstract} doSound(): void
}


abstract class domain::pets::Pet {
    # name: String
    ---
    + getName(): String
    + setName(name: String)
}

class domain::pets::Dog {
    - dogId: String
    ---
    + getDogId(): String
    + doSound(): void
}

class domain::pets::Cat {
    - fleaCollar
    ---
    + hasFleaCollar(): boolean
    + setFleaCollar(fleaCollar: boolean): void
    + doSound(): void
}
note left of Cat::fleaCollar
Flohhalsband
end note

Animal <|-- Pet
Pet <|-- Dog
Pet <|-- Cat

class ui::AnimalTableView


class ui::AnimalViewController {
    - model: AnimalModel
}

interface service::AnimalModelInterface {
    {Abstract} + addAnimal(animal: Animal)
    {Abstract} + removeAnimal((animal: Animal)
    {Abstract} + allAnimals()
    {Abstract} + getAnimalWithId(id: long)
}

class service::AnimalModel {
    - animals: List<Animal>
}

AnimalTableView <- AnimalViewController
AnimalViewController --> AnimalModelInterface
AnimalModelInterface <|.. AnimalModel
AnimalModel -> Animal

class MainApplication {
    - run()
    + main(args: String[])
}

@enduml