@startuml
'https://plantuml.com/class-diagram

class Application

abstract Parent

Application --> Parent

Parent --> BorderPane

BorderPane --> ImageView

BorderPane --> VBox

VBox --> Label

VBox --> TextField

@enduml