@startuml
'https://plantuml.com/class-diagram

class Client

abstract Component {
    draw()
}

Client --> Component

class Leaf {
draw()
}

Component <|-- Leaf

class Composite {
children[]: Component
---
addChildren(children: Component[])
getChildren(): Component[]
draw()
}

Component <|-- Composite

@enduml